### ISSUE TITLE
Package @bam.tech/react-native-make has been ignored because it contains invalid configuration

### ISSUE THREAD

**Issue by mcoeur** [bamlab/react-native-make#11]
Hello,

Context :
Platform : MacOS
```shell
$react-native -v
react-native-cli: 2.0.1
react-native: 0.60.4
```

I get this error when i run the following command :
```shell
react-native set-splash --path src/assets/logo.png --background "#f9f4f0" --resize center
```

```shell
warn Package @bam.tech/react-native-make has been ignored because it contains invalid configuration. Reason: Cannot find module '/Users/mcoeur/Documents/Dev/MyApp/node_modules/@react-native-community/cli/package.json'
Require stack:
- /Users/mcoeur/Documents/Dev/MyApp/node_modules/@bam.tech/react-native-make/dist/rn-plugin.config.js
- /Users/mcoeur/Documents/Dev/MyApp/node_modules/@bam.tech/react-native-make/react-native.config.js
- /Users/mcoeur/Documents/Dev/MyApp/node_modules/import-fresh/index.js- /Users/mcoeur/Documents/Dev/MyApp/node_modules/cosmiconfig/dist/loaders.js
- /Users/mcoeur/Documents/Dev/MyApp/node_modules/cosmiconfig/dist/createExplorer.js
- /Users/mcoeur/Documents/Dev/MyApp/node_modules/cosmiconfig/dist/index.js
- /Users/mcoeur/Documents/Dev/MyApp/node_modules/react-native/node_modules/@react-native-community/cli/build/tools/config/readConfigFromDisk.js
- /Users/mcoeur/Documents/Dev/MyApp/node_modules/react-native/node_modules/@react-native-community/cli/build/tools/config/index.js
- /Users/mcoeur/Documents/Dev/MyApp/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/install/install.js
- /Users/mcoeur/Documents/Dev/MyApp/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/index.js
- /Users/mcoeur/Documents/Dev/MyApp/node_modules/react-native/node_modules/@react-native-community/cli/build/cliEntry.js
- /Users/mcoeur/Documents/Dev/MyApp/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js
- /Users/mcoeur/Documents/Dev/MyApp/node_modules/react-native/cli.js
- /Users/mcoeur/.nvm/versions/node/v12.8.0/lib/node_modules/react-native-cli/index.js
error Unrecognized command "set-splash".
info Run "react-native --help" to see a list of all available commands.
```

I followed this blog post to install everything : https://blog.bam.tech/developper-news/set-up-your-react-native-splash-screen-in-15-minutes

What did I miss ?

**Comment by yleflour** [comment]
Linked to #6 , plugin is currently incompatible with npm (yarn only) a fix is being developed

**Comment by huangtony** [comment]
I'm still having this problem using 1.0.3 and `react-native set-splash --path logo.png --resize center`.

```
warn Package @bam.tech/react-native-make has been ignored because it contains invalid configuration. Reason: Unexpected token {
```
Installed using `yarn add -D @bam.tech/react-native-make`.

```
react-native-cli: 2.0.1
react-native: 0.61.1
```
At first I installed it on `react-native 0.60.5`, uninstalled it, upgraded to `0.61.1`, reinstalled but still have the same issue. I don't see the commands in `react-native -h` either.

**Comment by yleflour** [comment]
Thanks for the feedback. I will try making this plugin available through
command line under the `rnmake` alias

**Comment by logicallydimp23** [comment]
@huangtony try to use v1.02 `yarn add -D @bam.tech/react-native-make@1.0.2`
It worked with react-native version 0.61.2

**Comment by huangtony** [comment]
@logicallydimp23 Thanks, v1.02 worked fine.

**Comment by yleflour** [comment]
Hello, @mcoeur , can you tell me your react-native-cli package.json local install path within your project? It seems that I haven't handled all possibilities

**Comment by tomeberle** [comment]
Having this issue as well with RN 0.60.5 / npm install..

**Comment by logicallydimp23** [comment]
> Having this issue as well with RN 0.60.5 / npm install..

@tomeberle as a workaround have you tried v1.0.2?
`yarn add -D @bam.tech/react-native-make@1.0.2`

**Comment by tomeberle** [comment]
@logicallydimp23 Yes, but I had issues as well as the project is using npm and not yarn. Specifically, the yarn install was failing on MS Appcenter.

**Comment by yleflour** [comment]
@logicallydimp23 Can you give me:

- Using npm or yarn?
- Which version ?
- Which react-native-cli version ?
- Which react-native (project version) ?

**Comment by yleflour** [comment]
By the way, I need all the help I can get solving this issue.

For your information, previous invalid configuration errors were because  @react-native-community/cli/package.json couldn't be resolved.

Currently supported paths (cwd is your react-native project directory):

- node_modules/@react-native-community/cli/package.json (yarn)
- node_modules/react-native/node_modules/@react-native-community/cli/package.json (npm)

If your path doesn't match either of those, can you tell me:

- What your path actually is
- What your os, node, npm, yarn, RN, RN-cli versions are

**Comment by logicallydimp23** [comment]
@yleflour 
- Using npm or yarn? `Yarn`
- Which version ? `Yarn v1.17.3`, `@bam.tech/react-native-make v1.0.2`
- Which react-native-cli version ? `react-native-cli: 2.0.1`
- Which react-native (project version) ? `react-native: 0.60.5`

**Comment by finnp** [comment]
I went to the `node_modules/@bam.tech/react-native-make/dist/rn-plugin.config.js` file and removed the V1 detection script:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("colors");
const modules_1 = require("./modules");
const path_1 = require("path");
const rn_compatibility_layer_1 = require("./rn-compatibility-layer");
const v2Config = {
    commands: [modules_1.setIconCommand, modules_1.setSplashScreenCommand],
};
exports.rnPluginConfig = v2Config;
```

After that it was working correctly. 

Maybe you can just deprecate v1?
