### ISSUE TITLE
[Feature] Support Monorepo ?

### ISSUE THREAD

**Issue by fortezhuo** [bamlab/react-native-make#12]
How to use this CLI while we use RN monorepo package like : https://github.com/brunolemos/react-native-web-monorepo/ ?

**Comment by yleflour** [comment]
Hello, have you tried installing, and running it from the `packages/mobile` folder?

**Comment by fortezhuo** [comment]
Yes. I have tried, but while I install from package/mobile, the module will be installed on root of project, and while I run react-native -h, the new commands (set-icon / set-splash) don't exist

**Comment by yleflour** [comment]
Unfortunately I haven't been able to reproduce this issue.

It seems to be a problem with your environment setup and/or package manager. There is nothing I do at install time to force hoist to the parent package.

Can you:

- Copy paste the install command you're using
- Your directory structure
- The package manager you're using (and it's version)
- Try the install command with another dev-dependency

**Comment by firdausious** [comment]
@fortezhuo @yleflour perhaps you need to specify `nohoist` options in your root package.json

```javascript
{
   "workspaces":{
      "packages":[
         "packages/*"
      ],
      "nohoist":[
         "**/@bam.tech/react-native-make",
         "**/@bam.tech/react-native-make/**",
         "**/react-native",
         "**/react-native/**"
      ]
   }
}
```

**Comment by fortezhuo** [comment]
sorry for late response.. @firdausious provides great solution.
