### ISSUE TITLE
resource style/SplashScreen_SplashTheme not found

### ISSUE THREAD

**Issue by JohnBerd** [bamlab/react-native-make#30]
Thanks for this great module. I used it to install the app Icon and it worked like a charm.

When I type this command:
`react-native set-splash --path ~/Documents/icon.png --resize center --background "#b2eaff"`
and then:
`react-native run-android`

The project fail to compile with that error:

```
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  error: resource style/SplashScreen_SplashTheme (aka com.sally:style/SplashScreen_SplashTheme) not found.
  error: failed linking references.

```

**Comment by JohnBerd** [comment]
My bad, react-native-splash-screen wasn't installed

**Comment by aos83137** [comment]
How did you solve it

**Comment by JohnBerd** [comment]
By installing react-native-splash-screen

**Comment by julitroalves** [comment]
LOL, same issue here and installing **react-native-splash-screen** resolved my problem.
I'm tired this is the issue. hahahahhahahhahahahhahahha
