### ISSUE TITLE
black splash screen on iOS 14, iPhone 8 Plus

### ISSUE THREAD

**Issue by dev-yakuza** [bamlab/react-native-make#44]
First, thanks for making a great library.

Recently, I updated iOS version (13 -> 14). Suddenly Splash screen is not shown up on iPhone 8 Plus (Device and Simulator, both)

I am not sure this is react-native-make bug.

With the image

![Screen Shot 2020-09-19 at 10 03 04](https://user-images.githubusercontent.com/42969906/93655614-93661780-fa5f-11ea-8cf0-ca8bbe3c13d3.jpg)

Without the image

![Screen Shot 2020-09-19 at 10 03 31](https://user-images.githubusercontent.com/42969906/93655618-9e20ac80-fa5f-11ea-8963-1a6a43571e7f.jpg)

other simulators are ok.

**Comment by dev-yakuza** [comment]
I think it's not a good solution, but using the transparent background image solves the problem.

the splash image has only the logo, and execute the command below to solve the problem.

```bash
react-native set-splash --path ./src/env/splash.png --resize cover --background "#EC174F"
```

**Comment by Juliocbr** [comment]
Adding to what @dev-yakuza  mentioned I also had to uninstall my app and restart my iphone
