### ISSUE TITLE
Question: react-native android app icons: why isn't the empty space around the image preserved?

### ISSUE THREAD

**Issue by rahamin1** [bamlab/react-native-make#50]
I have created icons for a react-native app on android.

For example, this is the xxxhdpi icon. The black frame is not part of the image.  
It is just for showing the white margins around it:

[![xxxhdpi][1]][1]

When I install the app, the white margins are removed and the image is displayed as follows on Android 8 (the black background is the wallpaper):

[![icon on android][2]][2]

I expected the white margins to be kept. How do I keep it?

---

Image by <a href="https://pixabay.com/users/peri_priatna-8463731/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3364909">Peri Priatna</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3364909">Pixabay</a>

  [1]: https://i.stack.imgur.com/deqBd.png
  [2]: https://i.stack.imgur.com/amCAW.png

**Comment by Juliocbr** [comment]
@rahamin1  You have to use adaptive icons for android, so that the icon adapts to a circular shape, with rounded edges, etc.
In the documentation there is a link to review just the topic:
https://medium.com/google-design/designing-adaptive-icons-515af294c783

**Comment by rahamin1** [comment]
Thanks @Juliocbr , but isn't this package supposed to do the work for me?

**Comment by rahamin1** [comment]
I ended using https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html
